---
title: "2076 in calendar"
author: Deependra Dhakal
date: '2018-11-04'
slug: calendar
categories:
  - R
tags:
  - Dates
header:
  caption: ''
  image: ''
---

```{r setup, include=FALSE}
library(tidyverse)
require(lubridate)
knitr::opts_chunk$set(tidy = TRUE, cache = TRUE, 
                      echo = TRUE, 
                      tidy.opts = list(width.cutoff=50), 
                      eval = TRUE, 
                      fig.show = "hold", fig.align = "center", fig.width = 10,
                      fig.asp = 0.8, message = FALSE, warning = FALSE)
options(knitr.kable.NA = "", digits = 3)
require(showtext)
font_add("Preeti", "./fonts/PREETI_0.TTF")
showtext_auto(enable = TRUE)
```


```{r calendar-plot}
# import calendar data
calendar <- readxl::read_xlsx("./year_2076.xlsx", "year_2076") %>% 
  mutate(English_date = as.Date(English_date, "%d-%b-%y"))

nepali_months <- unique(calendar$Nepali_month)

calendar_2076vis <- map(.x = nepali_months,
                        .f = function(x){
                          month_nep <- x
                          year_nep <- "2076"
                          
                          dates <- calendar %>% 
                            filter(Nepali_month == month_nep, Nepali_year == year_nep) %>% 
                            select(English_date) %>% 
                            timetk::tk_augment_timeseries_signature() %>%
                            left_join(calendar %>% 
                                        select(English_date, contains("Nepali"), Observance) %>% 
                                        mutate_at("Observance", function(x)str_wrap(x,width = 18))) %>% 
                            mutate(mweek = as.numeric(interaction(-mweek, fct_rev(month.lbl)))) %>% 
                            mutate(mweek = case_when(
                              # capture the second element of the middle week
                              mweek >= (((mweek %>% table())[2:(length(mweek %>% table())-1)] < 7) %>% 
                                          which())[2] %>% 
                                names() %>% 
                                as.numeric() ~ mweek - 1,
                              TRUE ~ as.numeric(mweek)
                            )) %>% 
                            mutate(mweek = if_else(Nepali_month == "Poush", case_when(
                              mweek == 59~3, 
                              mweek == 58~2,
                              mweek == 57~1, 
                              mweek == 1~3, 
                              mweek == 2~4, 
                              mweek == 3~5, 
                              TRUE ~ mweek
                            ), mweek)
                            )
                          
                          # reduce all elements equal or great to second element by 1
                          
                          ggplot(dates, aes(x=wday.lbl, y=mweek)) + 
                            geom_tile(colour = "black", fill = "turquoise", alpha = 0.8) +
                            geom_text(aes(label=Nepali_day), size = 18, alpha = 0.5, 
                                      color = "red", check_overlap = FALSE, nudge_y = -0.35) +
                            geom_text(aes(label=Observance, family = "Preeti", lineheight = 0.4), size = 7, alpha = 1, 
                                      color = "blue", check_overlap = FALSE, nudge_y = +0.1) +
                            geom_text(aes(label=`Lunar day nepali`, family = "Preeti", 
                                          lineheight = 0.45), size = 7, alpha = 1, 
                                      color = "blue", check_overlap = FALSE, angle = 90, nudge_x = -0.42) +
                            scale_x_discrete(expand = c(0,0)) +
                            # labs(title = paste(month_nep, year_nep, sep = " ")) +
                            theme(title = element_text(size = 16), 
                                  axis.ticks = element_blank(),
                                  axis.title.y = element_blank(), 
                                  axis.text.y = element_blank(),
                                  axis.title.x = element_blank(),
                                  axis.text.x = element_text(size = 14),
                                  panel.background = element_rect(fill = "transparent"), 
                                  legend.position = "none"
                            )
                        }
)

purrr::walk2(.x = paste(1:length(nepali_months), "-", "Calendar_", nepali_months, "_2076", ".png", sep = ""),
             .y = calendar_2076vis,
             .f = ~ggsave(.x,
                          plot = .y, device = "png", width = 8,
                          height = 6, units = "in",
                          dpi = 200))
```

